CLASS zcl_15_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC for events of Z15_R_TRAVEL.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_15_handler IMPLEMENTATION.
ENDCLASS.
